### ISSUE TITLE
Microsoft Graph permissions

### ISSUE THREAD

**Issue by Ivanov1944** [jasperbaes/Microsoft-Cloud-Group-Analyzer#2]
Hi Jasper

The script looks great and I am trying to configure it, however I am stucked at Microsoft Graph permissions. 

What I do: I start node.js command prompt, I use "az login" command and the browser sign-in windows comes up. 
After I log in using global admin credentials, I start the script. 

Now, after I type "all", the script appears to get all the Entra groups from my tenant (I see the list with all the groups). However, at the end there is always an error message (see below).

I thought I granted all the necessary permissions to Graph Explorer (Delegated and Application permissions). But apparently something is missing. 

Can you share some info about the Graph Permissions that you configured?

 ERROR: you don't have permissions to read below 12 API endpoints:
[
  'https://graph.microsoft.com/beta/deviceManagement/deviceEnrollmentConfigurations?$expand=assignments',
  'https://graph.microsoft.com/beta/deviceManagement/deviceCompliancePolicies?$expand=assignments',
  'https://graph.microsoft.com/beta/deviceManagement/configurationPolicies?$expand=assignments',
  'https://graph.microsoft.com/beta/deviceManagement/deviceConfigurations?$expand=assignments',
  'https://graph.microsoft.com/beta/deviceManagement/deviceManagementScripts?$expand=assignments',
  'https://graph.microsoft.com/beta/deviceAppManagement/targetedManagedAppConfigurations?$expand=assignments',
  'https://graph.microsoft.com/beta/deviceAppManagement/mdmWindowsInformationProtectionPolicies?$expand=assignments',
  'https://graph.microsoft.com/beta/deviceAppManagement/iosManagedAppProtections?$expand=assignments',
  'https://graph.microsoft.com/beta/deviceAppManagement/androidManagedAppProtections?$expand=assignments',
  'https://graph.microsoft.com/beta/deviceAppManagement/windowsInformationProtectionPolicies?$expand=assignments',
  'https://graph.microsoft.com/beta/deviceManagement/windowsAutopilotDeploymentProfiles?$expand=assignments',
  'https://graph.microsoft.com/beta/policies/authenticationMethodsPolicy'

**Comment by jasperbaes** [comment]
Hi @Ivanov1944 

I did not anticipate that this script would gain so much traction and interest, hence my limited effort in documentation. I've just updated the main branch. Please take a moment to review the updated setup documentation, apply it to your environment, and then test again. If you encounter any issues, please let me know. 

For now, I recommend using an Azure App Registration, not user authentication. The reason for this is that user authentication (az login) uses the 'Microsoft Azure CLI' application, but the permissions of this app cannot be modified. Consequently, it is (currently) not possible to apply permissions for reading Intune to that application.

**Comment by Ivanov1944** [comment]
Thanks Jasper, I configured it according to your instructions and now it works like a charm :). 

BTW. A colleague of mine from Israel posted your script and I copied it from him and posted internally for my team (I am from Switzerland). So your solution became worldwide already :)

**Comment by jasperbaes** [comment]
Great to hear! Enjoy the script :))
